GET http://localhost:4000/services HTTP/1.1
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaXNhaSIsImxhc3RfbmFtZSI6IkRlbGdhZG8iLCJyb2xlIjoxLCJpYXQiOjE2MDY4NzE0NjQsImV4cCI6MTYwNjk1Nzg2NH0.fFKNY_LuuOJltdfLxNW6QYRKjgi-H1OV7vecBVb58u8
