GET http://localhost:4000/services HTTP/1.1
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaXNhaSIsImxhc3RfbmFtZSI6IkRlbGdhZG8iLCJyb2xlIjoxLCJpYXQiOjE2MDY3NTY1NTYsImV4cCI6MTYwNjg0Mjk1Nn0.d0RS9ETsfUepc5OYCsXR7CXyK9n_3vDC6td64XHNcIM
