GET http://localhost:4000/services HTTP/1.1
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaXNhaSIsImxhc3RfbmFtZSI6IkRlbGdhZG8iLCJyb2xlIjoxLCJpYXQiOjE2MDczMDQ2NzAsImV4cCI6MTYwNzM5MTA3MH0.PR3edN61Fx9DNDVlffkwG-f2CHAInt701b616K7KxGA
