POST http://localhost:4000/citas HTTP/1.1
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY2xpZW50ZSIsImxhc3RfbmFtZSI6InBydWViYSIsInJvbGUiOjMsImlhdCI6MTYwNzAyMjQ3MCwiZXhwIjoxNjA3MTA4ODcwfQ.qs60_eFxN32p8vVrIW4HC1UH82sjMFs_WLKV2DTIHjE

{
    "date_rsvp": "20-dic-2020",
    "comments": "pintura en el pelo",
    "user_FK": 25,
    "employee_FK": 24,
    "serviceType": 2
}