POST http://localhost:4000/citas HTTP/1.1
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaXNhaSIsImxhc3RfbmFtZSI6IkRlbGdhZG8iLCJyb2xlIjoxLCJpYXQiOjE2MDczMDMxMTgsImV4cCI6MTYwNzM4OTUxOH0.-gJEtinpdDSEAvWcd_HORMzsP2CbWcT0yMR-fG4PEWs

{
    "date_rsvp": "31-dic-2020",
    "comments": "lindas",
    "user_name": "yolanda mejias",
    "employee_name": "empleado",
    "serviceType": "uñas"
}