PUT http://localhost:4000/user/role/update HTTP/1.1
Authorization: jwt yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaXNhaSIsImxhc3RfbmFtZSI6IkRlbGdhZG8iLCJyb2xlIjoxLCJpYXQiOjE2MDczMTE4NTIsImV4cCI6MTYwNzM5ODI1Mn0.Qiwc3t0arGE8ljjqlP6W-XJvfRQhVZKHq5wVYebyElo
Content-Type: application/json


{"id": 1, "role": 1}